name: Build Geode Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Geode CLI
        uses: geode-sdk/cli-action@v2
        with:
          sdk: nightly

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EvenMoreDifficulties-Android
          path: "*.geode"
